### ISSUE TITLE
Statis Question

### ISSUE THREAD

**Issue by ghost** [Nolanlemahn/ProjectExist#15]
I’m wondering if you need any help or it is going to be worked on at a later time?

**Comment by Nolanlemahn** [comment]
Thank you for the kind inquiry.

My wish is to eventually pick up the project at some point, but as of current, that isn't feasible. (Temporary hiatus,)

When the team was last speaking with each other, we were primarily hurting on writers and editors.

~Nolan

**Comment by XavierDD1st** [comment]
I could help with writing
